name: Bug Report
description: Report an issue with the project
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: unitas_version
    attributes:
      label: UniTAS version
      description: What version of UniTAS are you using?
      options:
        - v0.2.0
        - v0.1.0
        - Latest master
        - Other (specify in additional context)
    validations:
      required: false
  - type: dropdown
    id: unitas_setup_tool
    attributes:
      label: UniTAS setup tool
      description: What setup tool did you use to install UniTAS? (If you did)
      options:
        - v1.1.3
        - v1.1.2
        - v1.1.1
        - Other (specify in additional context)
    validations:
      required: false
  - type: dropdown
    id: bepinex_version
    attributes:
      label: BepInEx version
      description: What version of BepInEx are you using?
      options:
        - v5.4.x
        - v5.3
        - v5.2
        - v5.1
        - v5.0.1
        - v5.0
        - Other (specify in additional context)
  - type: textarea
    id: game_name
    attributes:
      label: Game name
      description: What game are you trying to use UniTAS with?
    validations:
      required: true
  - type: dropdown
    id: game_build
    attributes:
      label: Game build
      description: What is the game build?
      options:
        - Windows x64 - Mono
        - Windows x86 - Mono
        - Linux x64 - Mono
        - Linux x86 - Mono
        - Other (specify in additional context)
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: This is the log output from UniTAS. You can find it in {GAME_DIR}/BepInEx/LogOutput.log
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.