using UniTAS.Patcher.Services.VirtualEnvironment.Input.LegacyInputSystem;

namespace UniTAS.Patcher.Implementations.VirtualEnvironment.InputState.LegacyInputSystem;

public class ControllerButtonStateEnvLegacyInputSystem : IControllerButtonStateEnvLegacyInputSystem
{
}