//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\source\repos\UniTAS\Plugin\MovieScriptDefaultGrammer.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MovieScriptDefaultGrammerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IMovieScriptDefaultGrammerListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MovieScriptDefaultGrammerParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MovieScriptDefaultGrammerParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.actionSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionSeparator([NotNull] MovieScriptDefaultGrammerParser.ActionSeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.actionSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionSeparator([NotNull] MovieScriptDefaultGrammerParser.ActionSeparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] MovieScriptDefaultGrammerParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] MovieScriptDefaultGrammerParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.actionWithSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionWithSeparator([NotNull] MovieScriptDefaultGrammerParser.ActionWithSeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.actionWithSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionWithSeparator([NotNull] MovieScriptDefaultGrammerParser.ActionWithSeparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.frameAdvance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrameAdvance([NotNull] MovieScriptDefaultGrammerParser.FrameAdvanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.frameAdvance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrameAdvance([NotNull] MovieScriptDefaultGrammerParser.FrameAdvanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.breakAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakAction([NotNull] MovieScriptDefaultGrammerParser.BreakActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.breakAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakAction([NotNull] MovieScriptDefaultGrammerParser.BreakActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.continueAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueAction([NotNull] MovieScriptDefaultGrammerParser.ContinueActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.continueAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueAction([NotNull] MovieScriptDefaultGrammerParser.ContinueActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.returnAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnAction([NotNull] MovieScriptDefaultGrammerParser.ReturnActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.returnAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnAction([NotNull] MovieScriptDefaultGrammerParser.ReturnActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] MovieScriptDefaultGrammerParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] MovieScriptDefaultGrammerParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAssignment([NotNull] MovieScriptDefaultGrammerParser.VariableAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAssignment([NotNull] MovieScriptDefaultGrammerParser.VariableAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variableTupleSeparation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableTupleSeparation([NotNull] MovieScriptDefaultGrammerParser.VariableTupleSeparationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.variableTupleSeparation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableTupleSeparation([NotNull] MovieScriptDefaultGrammerParser.VariableTupleSeparationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.tupleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleExpression([NotNull] MovieScriptDefaultGrammerParser.TupleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.tupleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleExpression([NotNull] MovieScriptDefaultGrammerParser.TupleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MovieScriptDefaultGrammerParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MovieScriptDefaultGrammerParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.mathOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathOpType([NotNull] MovieScriptDefaultGrammerParser.MathOpTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.mathOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathOpType([NotNull] MovieScriptDefaultGrammerParser.MathOpTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.logicOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicOpType([NotNull] MovieScriptDefaultGrammerParser.LogicOpTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.logicOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicOpType([NotNull] MovieScriptDefaultGrammerParser.LogicOpTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.binaryOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOpType([NotNull] MovieScriptDefaultGrammerParser.BinaryOpTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.binaryOpType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOpType([NotNull] MovieScriptDefaultGrammerParser.BinaryOpTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.intValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntValue([NotNull] MovieScriptDefaultGrammerParser.IntValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.intValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntValue([NotNull] MovieScriptDefaultGrammerParser.IntValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.intDigit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntDigit([NotNull] MovieScriptDefaultGrammerParser.IntDigitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.intDigit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntDigit([NotNull] MovieScriptDefaultGrammerParser.IntDigitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatValue([NotNull] MovieScriptDefaultGrammerParser.FloatValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatValue([NotNull] MovieScriptDefaultGrammerParser.FloatValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.floatDigit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatDigit([NotNull] MovieScriptDefaultGrammerParser.FloatDigitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.floatDigit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatDigit([NotNull] MovieScriptDefaultGrammerParser.FloatDigitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolValue([NotNull] MovieScriptDefaultGrammerParser.BoolValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.boolValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolValue([NotNull] MovieScriptDefaultGrammerParser.BoolValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] MovieScriptDefaultGrammerParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] MovieScriptDefaultGrammerParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.ifElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElse([NotNull] MovieScriptDefaultGrammerParser.IfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.ifElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElse([NotNull] MovieScriptDefaultGrammerParser.IfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] MovieScriptDefaultGrammerParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] MovieScriptDefaultGrammerParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCallArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallArgs([NotNull] MovieScriptDefaultGrammerParser.MethodCallArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCallArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallArgs([NotNull] MovieScriptDefaultGrammerParser.MethodCallArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCallArgsSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallArgsSeparator([NotNull] MovieScriptDefaultGrammerParser.MethodCallArgsSeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodCallArgsSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallArgsSeparator([NotNull] MovieScriptDefaultGrammerParser.MethodCallArgsSeparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDef([NotNull] MovieScriptDefaultGrammerParser.MethodDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDef([NotNull] MovieScriptDefaultGrammerParser.MethodDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodName([NotNull] MovieScriptDefaultGrammerParser.MethodNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodName([NotNull] MovieScriptDefaultGrammerParser.MethodNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDefArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDefArgs([NotNull] MovieScriptDefaultGrammerParser.MethodDefArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDefArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDefArgs([NotNull] MovieScriptDefaultGrammerParser.MethodDefArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDefArgsSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDefArgsSeparator([NotNull] MovieScriptDefaultGrammerParser.MethodDefArgsSeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.methodDefArgsSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDefArgsSeparator([NotNull] MovieScriptDefaultGrammerParser.MethodDefArgsSeparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.scopeOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopeOpen([NotNull] MovieScriptDefaultGrammerParser.ScopeOpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.scopeOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopeOpen([NotNull] MovieScriptDefaultGrammerParser.ScopeOpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.scopeClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopeClose([NotNull] MovieScriptDefaultGrammerParser.ScopeCloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.scopeClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopeClose([NotNull] MovieScriptDefaultGrammerParser.ScopeCloseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] MovieScriptDefaultGrammerParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] MovieScriptDefaultGrammerParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.roundBracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoundBracketOpen([NotNull] MovieScriptDefaultGrammerParser.RoundBracketOpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.roundBracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoundBracketOpen([NotNull] MovieScriptDefaultGrammerParser.RoundBracketOpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.roundBracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoundBracketClose([NotNull] MovieScriptDefaultGrammerParser.RoundBracketCloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.roundBracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoundBracketClose([NotNull] MovieScriptDefaultGrammerParser.RoundBracketCloseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.squareBracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSquareBracketOpen([NotNull] MovieScriptDefaultGrammerParser.SquareBracketOpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.squareBracketOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSquareBracketOpen([NotNull] MovieScriptDefaultGrammerParser.SquareBracketOpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.squareBracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSquareBracketClose([NotNull] MovieScriptDefaultGrammerParser.SquareBracketCloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.squareBracketClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSquareBracketClose([NotNull] MovieScriptDefaultGrammerParser.SquareBracketCloseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringIdentifier([NotNull] MovieScriptDefaultGrammerParser.StringIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringIdentifier([NotNull] MovieScriptDefaultGrammerParser.StringIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] MovieScriptDefaultGrammerParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] MovieScriptDefaultGrammerParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringChar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringChar([NotNull] MovieScriptDefaultGrammerParser.StringCharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammerParser.stringChar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringChar([NotNull] MovieScriptDefaultGrammerParser.StringCharContext context);
}
