//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MovieScriptDefaultGrammar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMovieScriptDefaultGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MovieScriptDefaultGrammarBaseListener : IMovieScriptDefaultGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] MovieScriptDefaultGrammarParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] MovieScriptDefaultGrammarParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] MovieScriptDefaultGrammarParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] MovieScriptDefaultGrammarParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.scopedProgram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScopedProgram([NotNull] MovieScriptDefaultGrammarParser.ScopedProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.scopedProgram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScopedProgram([NotNull] MovieScriptDefaultGrammarParser.ScopedProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.actionSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionSeparator([NotNull] MovieScriptDefaultGrammarParser.ActionSeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.actionSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionSeparator([NotNull] MovieScriptDefaultGrammarParser.ActionSeparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] MovieScriptDefaultGrammarParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] MovieScriptDefaultGrammarParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.actionWithSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionWithSeparator([NotNull] MovieScriptDefaultGrammarParser.ActionWithSeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.actionWithSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionWithSeparator([NotNull] MovieScriptDefaultGrammarParser.ActionWithSeparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.frameAdvance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameAdvance([NotNull] MovieScriptDefaultGrammarParser.FrameAdvanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.frameAdvance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameAdvance([NotNull] MovieScriptDefaultGrammarParser.FrameAdvanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.breakAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakAction([NotNull] MovieScriptDefaultGrammarParser.BreakActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.breakAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakAction([NotNull] MovieScriptDefaultGrammarParser.BreakActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.continueAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueAction([NotNull] MovieScriptDefaultGrammarParser.ContinueActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.continueAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueAction([NotNull] MovieScriptDefaultGrammarParser.ContinueActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.returnAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnAction([NotNull] MovieScriptDefaultGrammarParser.ReturnActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.returnAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnAction([NotNull] MovieScriptDefaultGrammarParser.ReturnActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] MovieScriptDefaultGrammarParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] MovieScriptDefaultGrammarParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssignment([NotNull] MovieScriptDefaultGrammarParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssignment([NotNull] MovieScriptDefaultGrammarParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleAssignment([NotNull] MovieScriptDefaultGrammarParser.TupleAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleAssignment([NotNull] MovieScriptDefaultGrammarParser.TupleAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variableTupleSeparation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableTupleSeparation([NotNull] MovieScriptDefaultGrammarParser.VariableTupleSeparationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.variableTupleSeparation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableTupleSeparation([NotNull] MovieScriptDefaultGrammarParser.VariableTupleSeparationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleVar([NotNull] MovieScriptDefaultGrammarParser.TupleVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleVar([NotNull] MovieScriptDefaultGrammarParser.TupleVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleExpression([NotNull] MovieScriptDefaultGrammarParser.TupleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.tupleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleExpression([NotNull] MovieScriptDefaultGrammarParser.TupleExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>andOr</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndOr([NotNull] MovieScriptDefaultGrammarParser.AndOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andOr</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndOr([NotNull] MovieScriptDefaultGrammarParser.AndOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parentheses</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParentheses([NotNull] MovieScriptDefaultGrammarParser.ParenthesesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parentheses</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParentheses([NotNull] MovieScriptDefaultGrammarParser.ParenthesesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multiplyDivide</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplyDivide([NotNull] MovieScriptDefaultGrammarParser.MultiplyDivideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplyDivide</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplyDivide([NotNull] MovieScriptDefaultGrammarParser.MultiplyDivideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot([NotNull] MovieScriptDefaultGrammarParser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot([NotNull] MovieScriptDefaultGrammarParser.NotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>compare</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompare([NotNull] MovieScriptDefaultGrammarParser.CompareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>compare</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompare([NotNull] MovieScriptDefaultGrammarParser.CompareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addSubtract</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubtract([NotNull] MovieScriptDefaultGrammarParser.AddSubtractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubtract</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubtract([NotNull] MovieScriptDefaultGrammarParser.AddSubtractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bitwise</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwise([NotNull] MovieScriptDefaultGrammarParser.BitwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bitwise</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwise([NotNull] MovieScriptDefaultGrammarParser.BitwiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bitwiseShift</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseShift([NotNull] MovieScriptDefaultGrammarParser.BitwiseShiftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bitwiseShift</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseShift([NotNull] MovieScriptDefaultGrammarParser.BitwiseShiftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>terminator</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminator([NotNull] MovieScriptDefaultGrammarParser.TerminatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>terminator</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminator([NotNull] MovieScriptDefaultGrammarParser.TerminatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>flipSign</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlipSign([NotNull] MovieScriptDefaultGrammarParser.FlipSignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>flipSign</c>
	/// labeled alternative in <see cref="MovieScriptDefaultGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlipSign([NotNull] MovieScriptDefaultGrammarParser.FlipSignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] MovieScriptDefaultGrammarParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] MovieScriptDefaultGrammarParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.intType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntType([NotNull] MovieScriptDefaultGrammarParser.IntTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.intType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntType([NotNull] MovieScriptDefaultGrammarParser.IntTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.floatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatType([NotNull] MovieScriptDefaultGrammarParser.FloatTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.floatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatType([NotNull] MovieScriptDefaultGrammarParser.FloatTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] MovieScriptDefaultGrammarParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] MovieScriptDefaultGrammarParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] MovieScriptDefaultGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] MovieScriptDefaultGrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfStatement([NotNull] MovieScriptDefaultGrammarParser.ElseIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfStatement([NotNull] MovieScriptDefaultGrammarParser.ElseIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] MovieScriptDefaultGrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] MovieScriptDefaultGrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] MovieScriptDefaultGrammarParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] MovieScriptDefaultGrammarParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodCallArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCallArgs([NotNull] MovieScriptDefaultGrammarParser.MethodCallArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodCallArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCallArgs([NotNull] MovieScriptDefaultGrammarParser.MethodCallArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDef([NotNull] MovieScriptDefaultGrammarParser.MethodDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDef([NotNull] MovieScriptDefaultGrammarParser.MethodDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodDefArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDefArgs([NotNull] MovieScriptDefaultGrammarParser.MethodDefArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.methodDefArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDefArgs([NotNull] MovieScriptDefaultGrammarParser.MethodDefArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] MovieScriptDefaultGrammarParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MovieScriptDefaultGrammarParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] MovieScriptDefaultGrammarParser.LoopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
