# NOTE: this exists because of https://github.com/federicocarboni/setup-ffmpeg/issues/19

name: 'Setup FFmpeg with retries'
description: 'Installs FFmpeg with retry logic'
inputs:
  github-token:
    description: 'GitHub Token (required by "FedericoCarboni/setup-ffmpeg@v3")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup FFmpeg
      id: attempt1
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        github-token: ${{ inputs.github-token }}

    - name: Setup FFmpeg (retry 2)
      if: ${{ steps.attempt1.outcome == 'failure' }}
      id: attempt2
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        github-token: ${{ inputs.github-token }}

    - name: Setup FFmpeg (retry 3)
      if: ${{ steps.attempt2.outcome == 'failure' }}
      id: attempt3
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        github-token: ${{ inputs.github-token }}
