name: Auto-merge
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automated:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'github-actions[bot]') && github.repository == 'Eddio0141/UniTASTestClients'
    steps:
      - name: Auto-merge for PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
